### ISSUE TITLE
moveto returns "unknown command" on v4.3.0 of chrome webdriver

### ISSUE THREAD

**Issue by vasilake-v** [instaclick/php-webdriver#118]
Hey All !

I'm trying to use the new version of "selenium/hub:4.3.0-20220726" and "selenium/node-chrome:4.3.0-20220726" with https://github.com/minkphp/MinkSelenium2Driver but facing a issue related to ["clickOnElement()"](https://github.com/minkphp/MinkSelenium2Driver/blob/master/src/Selenium2Driver.php#L794) method

_One could say/relay me to MinkSelenium2Driver package discussion, but i still think this is something related to php-webdriver and its method support for webdrivers._

During ["clickOnElement()"](https://github.com/minkphp/MinkSelenium2Driver/blob/master/src/Selenium2Driver.php#L794) method, on webdriver the **moveto** and **click()** is called. 
`php-webdriver` throws exception during **moveto()** action, after `POST http://127.0.0.1:4444/wd/hub/session/:sessionId/moveto`, which is accepted by selenium-hub... it returns a response with error details `"error": "command unknown"`

I've created a Pull-request but i'm not 100% sure whether the approach is the right one (seems to be though) https://github.com/instaclick/php-webdriver/pull/117

I'd appreciate some guidance here

Thank you!

**Comment by Saeven** [comment]
@slava-v I'm running into the same problem using:

* selenium/standalone-chrome:4.6.0-20221104
* "behat/behat": "3.12.0"
* "behat/mink": "v1.10.0"
* "behat/mink-extension": "2.3.1"
* "behat/mink-selenium2-driver": "v1.6.0"
* "instaclick/php-webdriver": "1.4.16"
* ChromeDriver 107.0.5304.62

Had you solved this? I get logs that look like:

```
#0 /Users/Saeven/Documents/Launchfire/code/Lemonade/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(174): WebDriver\Exception::factory(-8, 'Unable to execu...')
#1 /Users/Saeven/Documents/Launchfire/code/Lemonade/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(234): WebDriver\AbstractWebDriver->curl('POST', '/moveto', Array)
#2 /Users/Saeven/Documents/Launchfire/code/Lemonade/vendor/instaclick/php-webdriver/lib/WebDriver/Container.php(241): WebDriver\AbstractWebDriver->__call('moveto', Array)
#3 /Users/Saeven/Documents/Launchfire/code/Lemonade/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(798): WebDriver\Container->__call('moveto', Array)
```

**Comment by justafish** [comment]
I've opened a PR to fix this #120

**Comment by slava-v** [comment]
@Saeven 

The issue was fixed for me with `instaclick/php-webdriver: 1.4.15`

So my setup is slightly different

container image: selenium/node-chrome: 4.3.0-20220726

#### `composer.lock`
```
behat/behat: v3.10.0
behat/mink: v1.10.0
behat/mink-extension: 2.3.1
behat/mink-selenium2-driver: v1.6.0
instaclick/php-webdriver: 1.4.15
```

#### `behat.yml.dist`
```yaml
extensions:
        Behat\MinkExtension:
            sessions:
                default:
                    symfony2: ~
                javascript:
                    selenium2:
                        wd_host: "http://selenium-hub:4444/wd/hub" # Docker configuration
                        capabilities:
                            browserName: 'chrome'
                            marionette: false
                            browser: 'chrome'
                            platform: "LINUX"
                            version: ''
                            extra_capabilities:
                                idle-timeout: 600
                                command-timeout: 600
                                max-duration: 14400
                                chromeOptions:
                                    args:
                                        - "start-maximized"

```

#### `docker-compose.yml`
```yaml
    selenium-hub:
        image: selenium/hub:4.3.0-20220726
        ports:
            - "4444:4444"

    selenium-node-chrome:
        image: selenium/node-chrome:4.3.0-20220726
        volumes:
            - "${PROJECT_ROOT:-.}/var/chrome:/tmp/"
        ports:
@@ -91,9 +91,12 @@ services:
            SCREEN_DEPTH: 24
            NODE_MAX_SESSION: 1
            NODE_MAX_INSTANCES: 1
            SE_EVENT_BUS_HOST: selenium-hub
            SE_EVENT_BUS_PUBLISH_PORT: 4442
            SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        shm_size: 2G
        depends_on:
            - selenium-hub
```
