### ISSUE TITLE
Integrated proxy support

### ISSUE THREAD

**Issue by robocoder** [instaclick/php-webdriver#49]
This feature request is three-fold:
- allow for injection of custom headers in the request to Firefox
- expose the HTTP response code between Selenium and Firefox
- abstract the underlying proxy implementation

Desirable proxies to be supported:
- https://github.com/lightbody/browsermob-proxy
- https://code.google.com/p/zaproxy/

Note: Mink support for getStatusCode() is non-trivial because the Selenium server does not expose the HTTP response received by Firefox ([link](https://code.google.com/p/selenium/issues/detail?id=141)).

**Comment by mvorisek** [comment]
here is working demo for Behat config:

```
...
      sessions:
        default:
          selenium2:
            browser: chrome
            wd_host: 'http://127.0.0.1:4444/wd/hub'
            capabilities:
              extra_capabilities:
                chrome:
                  binary: '...'
                  args:
                    - '--headless'
                    - '--window-size=1280,720'
                proxy:
                  proxyType: manual
                  httpProxy: 10.10.10.10:2000
                  sslProxy: 10.10.10.10:2000
```

tested /w Firefox & Chrome, localhost is bypassed by default
